config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    member do
      get "add_click"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "boards#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :email, :name, presence: true
  validates :email, email: true, unless: -> { email.blank? }
  validates :width, :height, :mine_number, numericality: {only_integer: true, greater_than: 0}
  validate :is_playable?

  before_create :generate_bombs

  scope :ordered, -> { order(created_at: :desc) }
  scope :limit_ordered, -> { ordered.limit(10) }

  def difficulty
    return "Unknown" unless height && width && mine_number

    if density < 15
      "Easy"
    elsif density < 20
      "Intermediate"
    else
      "Hard"
    end
  end

  def dimensions
    "#{width} x #{height}"
  end

  def density
    (mine_number.to_f / (height * width) * 100).round(1)
  end

  def is_playable?
    return unless height && width && mine_number

    if density > 50
      errors.add(:mine_number, "is too large")
    end
  end

  def add_click(x, y, flag)
    if flag
      if flags.include?([x, y])
        flags.delete([x, y])
      else
        flags << [x, y]
      end
    elsif bombs.include?([x, y])
      self.game_over = true
    else
      clicks << [x, y]
      flags.delete([x, y])
    end
  end

  # algorithm for generating the board
  def generate_bombs
    temp_bombs = Set.new

    while temp_bombs.length < mine_number
      temp_bombs.add([rand(width), rand(height)])
    end

    self.bombs = temp_bombs.to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy add_click]

  # GET /boards or /boards.json
  def index
    if params[:all] == "true"
      @boards = Board.ordered
      @all = true
    else
      @boards = Board.limit_ordered
      @all = false
    end
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_click
    x = params[:x].to_i
    y = params[:y].to_i
    flag = params[:flag] == "true"

    if (0...@board.width).cover?(x) && (0...@board.height).cover?(y)
      @board.add_click(x, y, flag)
      @board.save
    end

    redirect_to board_path
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.require(:board).permit(:email, :width, :height, :mine_number, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tailwind_classes_for(flash_type)
    {
      success: "bg-yellow-400 border-l-4 border-yellow-500 text-black",
      notice: "bg-yellow-400 border-l-4 border-yellow-500 text-black",
      alert: "bg-red-400 border-l-4 border-red-700 text-black"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def bombs_near(set, x, y)
    near_array = []
    (x - 1..x + 1).each do |i|
      (y - 1..y + 1).each do |j|
        near_array << [i, j]
      end
    end
    count = set.intersection(near_array).count
    count.positive? ? count : ""
  end

  def bombs_near_color(set, x, y)
    case bombs_near(set, x, y)
    when 1
      "text-blue-700"
    when 2
      "text-green-700"
    when 3
      "text-red-700"
    when 4
      "text-indigo-900"
    when 5
      "text-orange-800"
    when 6
      "text-teal-600"
    when 7
      "text-black"
    when 8
      "text-gray-500"
    else
      ""
    end
  end

  def nicely_formatted_datetime(datetime)
    datetime.strftime("%-m/%-d/%y at %H:%M%P %Z")
  end

  def game_status_color(board)
    board.game_over? ? "text-red-500" : "text-blue-500"
  end
end

app/views/boards/_board.html.erb
<tr>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0">
    <%= link_to board.name, board_path(board), class: "#{game_status_color(board)}", data: { turbo: false } %>
  </td>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0"><%= board.email %></td>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0"><%= nicely_formatted_datetime(board.created_at) %></td>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0"><%= board.dimensions %></td>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0"><%= board.mine_number %></td>
  <td class="py-4 pl-4 pr-3 text-center text-sm font-medium text-gray-900 sm:pl-0"><%= board.difficulty %></td>
</tr>

app/views/boards/_form.html.erb
<%= form_with(model: board, class: "contents") do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul class="list-disc">
        <% board.errors.each do |error| %>
          <li class="ml-5"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :email, "Your email address" %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name, "Board name" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :width %>
    <%= form.number_field :width, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :height %>
    <%= form.number_field :height, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :mine_number, "Number of mines" %>
    <%= form.number_field :mine_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="mt-2 text-sm text-gray-500" id="email-description">Only densities of 50% or less are allowed.</p>
  </div>

  <div class="inline">
    <%= form.submit "Generate Board", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing board</h1>

  <%= render "form", board: @board %>

  <%= link_to "Show this board", @board, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to boards", boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/boards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Boards</h1>
    <%= link_to "New board", new_board_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="-mx-4 -my-2 overflow-x-visible sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <%= turbo_frame_tag "boards" do %>
        <table class="min-w-full divide-y divide-gray-300 pb-12">
          <thead>
          <tr>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Name</th>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">User</th>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Created at</th>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Dimensions</th>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Number of Mines</th>
            <th scope="col" class="py-3 pl-4 pr-3 text-center text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Difficulty</th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <%= render @boards %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

  <div class="my-5">
    <% if @all %>
      <%= link_to "View newest boards", boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% else %>
      <%= link_to "View all generated boards", boards_path(all: true), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Minesweeper Board</h1>

  <%= render "form", board: @board %>

  <%= link_to "Back to boards", boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/boards/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= @board.name %></h1>
  <p class="text-gray-700 italic">Created by <%= @board.email %> on <%= nicely_formatted_datetime(@board.created_at) %>.</pi>
  <div class="my-5">
    Directions
    <ul class="list-disc ml-7">
      <li>Click on the tiles to reveal them to be mines or blank tiles.</li>
      <li>Tiles that are blank list the number of mines near them (left, right, up, down, or diagonally next to).</li>
      <li>Hold Alt (Option on Mac) to flag a tile as a suspected mine.</li>
      <li>If you click on a mine, the game is over and the whole board will be revealed.</li>
    </ul>
  </div>

  <div class="my-5">
    <% @board.height.times do |y| %>
      <div class="flex items-center justify-center">
        <% @board.width.times do |x| %>
          <% if @board.game_over || @board.clicks.include?([x, y]) %>
            <div class="bg-gray-50 border border-gray-300 shadow-inner text-center w-6 h-6">
              <% if @board.bombs.include?([x, y]) %>
                <%= image_tag "bomb.png" %>
              <% else %>
                <span class="<%= bombs_near_color(@board.bombs, x, y) %>"><%= bombs_near(@board.bombs, x, y) %></span>
              <% end %>
            </div>
          <% else %>
            <div class="bg-gray-100 border border-gray-300 grid place-items-center w-6 h-6" data-controller="cell" data-cell-url-value="<%= "#{add_click_board_path(@board, x: x, y: y)}" %>" data-action="click->cell#click">
              <div class="bg-gray-200 shadow-2xl w-4 h-4">
                <% if @board.flags.include?([x, y]) %>
                  <%= image_tag "flag.jpeg" %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to "Back to boards", boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="alerts">
      <%= render "shared/alerts" %>
    </div>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% flash.each do |message| %>
  <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
    <div data-controller="alert" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="max-w-sm w-full shadow-lg px-4 py-3 rounded relative <%= tailwind_classes_for(message[0]) %> pointer-events-auto transition translate-x-full transform ease-in-out duration-1000 opacity-0">
      <div class="p-2">
        <div class="flex items-start">
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm leading-5 font-medium">
              <%= message[1] %>
            </p>
          </div>
          <div class="ml-4 flex-shrink-0 flex">
            <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>